runtime: python39

handlers:
  # Serve static files from the "static" directory
  - url: /static
    static_dir: static

  # Route all other requests to the Flask app
  - url: /.*
    script: auto
